services:
  jira_node_1:
    depends_on:
      postgresql:
        condition: service_healthy
      data-loader:
        condition: service_completed_successfully
    image: atlassian/jira-software:9.12.4
    networks:
      - jiranet
    volumes:
      - ./dev/jira-data:/var/atlassian/application-data/jira/shared
    ports:
      - '8080:8080'
      - '8000:8000'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/" ]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 120s
    environment:
      - 'ATL_JDBC_URL=jdbc:postgresql://postgresql:5432/jiradb'
      - 'ATL_JDBC_USER=jira'
      - 'ATL_JDBC_PASSWORD=jira'
      - 'ATL_DB_DRIVER=org.postgresql.Driver'
      - 'ATL_DB_TYPE=postgres72'
      - 'JVM_MINIMUM_MEMORY=2048m'
      - 'JVM_MAXIMUM_MEMORY=4096m'
      - 'JVM_SUPPORT_RECOMMENDED_ARGS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"'
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  postgresql:
    image: postgres:9.5-alpine
    networks:
      - jiranet
    volumes:
      - baton-jira-postgresqldata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=jira'
      - 'POSTGRES_PASSWORD=jira'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "jiradb", "-U", "jira" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s

  data-loader:
    image: postgres:9.5-alpine
    volumes:
      - ./data:/data
    networks:
      - jiranet
    environment:
      PGDATABASE: jiradb
      PGUSER: jira
      PGPASSWORD: jira
      PGHOST: postgresql
    command: sh /data/load.sh
    depends_on:
      postgresql:
        condition: service_healthy

volumes:
  baton-jira-postgresqldata:
    external: false

networks:
  jiranet:
    driver: bridge